spring.application.name=shandar
# Tell Spring to use a local SQLite file named pos_database.db
spring.datasource.url=jdbc:sqlite:pos_database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Use the community dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Automatically create the database tables based on our Java classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL in the console so we can see what the database is doing
spring.jpa.show-sql=true